fix: improve error handling for .env.docker in deployment workflow
- Added a check to ensure the .env.docker file exists before attempting to update the IMAGE_TAG.
- Included an error message and exit command if the file is not found, enhancing robustness of the deployment process.

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -82,8 +82,14 @@ jobs:
             aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
 
             echo "📝 [Env Update] Injection sequence: updating .env.docker with IMAGE_TAG=$IMAGE_TAG"
-            sed -i '/IMAGE_TAG/d' .env.docker
-            echo "IMAGE_TAG=$IMAGE_TAG" >> .env.docker
+            if [ -f .env.docker ]; then
+              sed -i '/IMAGE_TAG/d' .env.docker
+              echo "IMAGE_TAG=$IMAGE_TAG" >> .env.docker
+            else
+              # throw error
+              echo "🚨 [Error] .env.docker file not found"
+              exit 1
+            fi
 
             echo "📥 [Pull] Fetching the latest container versions from ECR registry..."
             docker compose -f docker-compose.prod.yaml pull
